In [1]:
from pandas import Series, DataFrame
import pandas as pd
%pylab inline
from textblob import TextBlob
from textblob.sentiments import NaiveBayesAnalyzer
df1 = pd.read_csv('wine1.csv')
df2 = pd.read_csv('wine2.csv')

Populating the interactive namespace from numpy and matplotlib

In [13]:
frames = [df1,df2]

df = pd.concat(frames, sort = True)
df["province country"] = df["province"] + ", " + df["country"]

df[0:10]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,province country
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,NaN,NaN,NaN,Cabernet Sauvignon,Heitz,"California, US"
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,NaN,NaN,NaN,Tinta de Toro,Bodega Carmen Rodríguez,"Northern Spain, Spain"
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,NaN,NaN,NaN,Sauvignon Blanc,Macauley,"California, US"
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,NaN,NaN,NaN,Pinot Noir,Ponzi,"Oregon, US"
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,NaN,NaN,NaN,Provence red blend,Domaine de la Bégude,"Provence, France"
5,5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,NaN,NaN,NaN,Tinta de Toro,Numanthia,"Northern Spain, Spain"
6,6,Spain,Slightly gritty black-fruit aromas include a s...,San Román,95,65.0,Northern Spain,Toro,NaN,NaN,NaN,NaN,Tinta de Toro,Maurodos,"Northern Spain, Spain"
7,7,Spain,Lush cedary black-fruit aromas are luxe and of...,Carodorum Único Crianza,95,110.0,Northern Spain,Toro,NaN,NaN,NaN,NaN,Tinta de Toro,Bodega Carmen Rodríguez,"Northern Spain, Spain"
8,8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,NaN,NaN,NaN,Pinot Noir,Bergström,"Oregon, US"
9,9,US,The producer sources from two blocks of the vi...,Gap's Crown Vineyard,95,60.0,California,Sonoma Coast,Sonoma,NaN,NaN,NaN,Pinot Noir,Blue Farm,"California, US"

In [3]:
def sentiment(description):
    des = TextBlob(description)
    return des.sentiment.polarity

In [4]:
#best/worst average by country


avg_country = df[["country","points"]].groupby("country").agg(["count","mean"])
avg_country.columns = ['Count', "Mean"]
avg_country = avg_country[avg_country["Count"] > 200]
avg_country.sort_values(by= "Mean", ascending = False)[0:5] #best
#avg_country.sort_values(by= "Mean", ascending = True)[0:5] #worst

         Count       Mean
country
Austria   6402  89.707591
Germany   4617  89.200996
France   43191  88.884559
Canada     453  88.880795
Italy    43018  88.481147

In [66]:
#best average by region
avg_region = df[["province country","points"]].groupby(["province country"]).agg(["count","mean"])

avg_region.columns = ['Count', "Mean"]
avg_region = avg_region[avg_region["Count"] > 100]

avg_region.sort_values(by="Mean", ascending = False)[0:5] #best

avg_region.sort_values(by="Mean", ascending = True)[0:5] #worst

                            Count       Mean
province country
New Mexico, US                140  83.950000
Central Valley, Chile         884  84.830317
Central Spain, Spain         1228  84.906352
Valle de Guadalupe, Mexico    122  84.909836
Australia Other, Australia    798  85.030075

In [67]:
#best average by varietal
avg_varietal = df[["variety","points"]].groupby(["variety"]).agg(["count",'mean'])

avg_varietal.columns = ['Count', "Mean"]
avg_varietal = avg_varietal[avg_varietal["Count"] > 100]


avg_varietal.sort_values(by="Mean", ascending = False)[0:5] #best
avg_varietal.sort_values(by="Mean", ascending = True)[0:5] #worst

                     Count       Mean
variety
Lambrusco              110  84.409091
Viura                  217  85.092166
Torrontés              617  85.202593
Chardonnay-Viognier    110  85.618182
Garnacha               727  85.656121

In [68]:
#best/worst bang per buck per country
df["BPB Score"] = df["points"]/df["price"]

bbp_country = df[["country","BPB Score"]].groupby("country").agg(["count","mean"])
bbp_country.columns = ['Count', "Mean"]

bbp_country2 = bbp_country[bbp_country["Count"] > 200]
bbp_country2.sort_values(by= "Mean", ascending = False)[0:5] #best
#bbp_country2.sort_values(by= "Mean", ascending = True)[0:5] #worst

           Count      Mean
country
Romania      259  8.249066
Bulgaria     218  7.488149
Chile      10182  5.938419
Argentina   9343  5.611222
Portugal    9051  5.554613

In [22]:
#per price range 
df["Price Range"] = pd.qcut(df["price"], 5)

price_range = df[["Price Range", "points"]].groupby("Price Range").agg(["count","max"])
price_range.columns = ["Count", "Max"]

df[0:10]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,province country,Price Range
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,NaN,NaN,NaN,Cabernet Sauvignon,Heitz,"California, US","(45.0, 3300.0]"
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,NaN,NaN,NaN,Tinta de Toro,Bodega Carmen Rodríguez,"Northern Spain, Spain","(45.0, 3300.0]"
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,NaN,NaN,NaN,Sauvignon Blanc,Macauley,"California, US","(45.0, 3300.0]"
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,NaN,NaN,NaN,Pinot Noir,Ponzi,"Oregon, US","(45.0, 3300.0]"
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,NaN,NaN,NaN,Provence red blend,Domaine de la Bégude,"Provence, France","(45.0, 3300.0]"
5,5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,NaN,NaN,NaN,Tinta de Toro,Numanthia,"Northern Spain, Spain","(45.0, 3300.0]"
6,6,Spain,Slightly gritty black-fruit aromas include a s...,San Román,95,65.0,Northern Spain,Toro,NaN,NaN,NaN,NaN,Tinta de Toro,Maurodos,"Northern Spain, Spain","(45.0, 3300.0]"
7,7,Spain,Lush cedary black-fruit aromas are luxe and of...,Carodorum Único Crianza,95,110.0,Northern Spain,Toro,NaN,NaN,NaN,NaN,Tinta de Toro,Bodega Carmen Rodríguez,"Northern Spain, Spain","(45.0, 3300.0]"
8,8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,NaN,NaN,NaN,Pinot Noir,Bergström,"Oregon, US","(45.0, 3300.0]"
9,9,US,The producer sources from two blocks of the vi...,Gap's Crown Vineyard,95,60.0,California,Sonoma Coast,Sonoma,NaN,NaN,NaN,Pinot Noir,Blue Farm,"California, US","(45.0, 3300.0]"

In [23]:
#$3.99 - $12
df[df["Price Range"] == "(45.0, 3300.0]"]

Empty DataFrame
Columns: [Unnamed: 0, country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery, province country, Price Range]
Index: []